version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: pip
    directory: /services/prana_api
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /services/prana_admin
    schedule:
      interval: weekly
  - package-ecosystem: pub
    directory: /apps/android
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/prana_api
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /services/prana_admin
    schedule:
      interval: weekly
  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
